### ISSUE TITLE
Agent should not be able to see through walls and doors

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [maximecb/baby-ai-game#10]
As discussed on slack

**Comment by maximecb** [comment]
I'm going to make it so there are "light beams" travelling forward from the agent's position. I will add some method to object classes, ie: `isOpaque()`, which will determine whether the agent can see behind those objects.

**Comment by maximecb** [comment]
Ok, so. I implemented a mechanism for this, but it turns out that simulating light or visibility in 2D is rather nontrivial/unintuitive. I think it would be simpler to keep things as they are for now.

I checked the code for preventing seeing through walls in a branch:
https://github.com/maximecb/gym-minigrid/commit/ed662a5597856202b9bcd0be88e3a186d99d7d73

**Comment by dmitriy-serdyuk** [comment]
Ok, no problem.

Do you mean, it is hard to decide if a given square in the grid is visible or not when, say, only 5% is visible? (some cool demonstrations: https://www.redblobgames.com/articles/visibility/)

**Comment by maximecb** [comment]
I mean it's quite a bit of code for what it does, and it's not super intuitive.

The way I did it is rule-based rather than based on raycasting though.
